dataset_name: pascal_voc
exp_dir: ./experiments
test_dataset_dir: /home/tony/Documents/datasets/sbd_dataset
test_name: train1.txt
num_classes: 21
type2: sbd
train_model: model1
ckpt_dir: checkpoint1
continue_train: True
init_checkpoint_file: fcn32s_bp_0
test_batch_size: 1
train_model: model1
global_step: 0
print_every: 5
