dataset_name: pascal_voc
exp_dir: ./experiments
train_dataset_dir: /4tb/tony_datasets/sbd_dataset
test_dataset_dir: /4tb/tony_datasets/sbd_dataset
train_name: train1.txt
test_name: train1.txt
num_classes: 21
type1: sbd
type2: sbd
train_model: model1
ckpt_dir: checkpoint1
init_checkpoint_file: None
batch_size: 1
test_batch_size: 1
train_model: model1
global_step: 0
start_step: 0
epochs: 175
summary_freq: 20
l_rate_decay_epoch: 40
l2: 0.0002
l_rate: 0.0001
